analytics: {}
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.410095
  lightness: 0
  rhythmicContrast: 0.066857
  saturation: 0.153353
cta: {}
layout_spectrum: 0.496621
name: spaces
opengraph: {}
purpose: {}
typography_spectrum: 0.938063
