name: spaces
favicon: null
layout_spectrum: 0.91813
typography_spectrum: 0.938063
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7a7150'
    - '#ada275'
    - '#0c0e0b'
    - '#6dd9fd'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.153353
  rhythmicContrast: 0.75
purpose:
  - name: null
    item: null
    url: null
