analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#7A7150'
    - '#ADA275'
    - '#0C0E0B'
    - '#6DD9FD'
  brandStrength: 0.75
  lightness: 0
  rhythmicContrast: 0.75
  saturation: 0.153353
cta: {}
layout_spectrum: 0.91813
name: spaces
opengraph: {}
purpose:
  - {}
typography_spectrum: 0.514639
